### PR TITLE
Some creative mode enchancements

### PR DESCRIPTION
**Pull request by ssdaniel24**
When creative mode:
- infinite canvases
- infinite brushes

### CODE REVIEW

**Comment by sfence** [comment]
Looks to be working well. Please rebase/fix conflict.

**Comment by ssdaniel24** [comment]
@sfence, done!

**Comment by alek13** [comment]
@sfence can you merge this ?

**Comment by sfence** [comment]
Sorry, I forget about this.
Thank you for the reminder.

**Pull request merged**
